name: deeplearningproject
channels:
- defaults
dependencies:
- backports=1.0=py27_0
- backports_abc=0.5=py27_0
- decorator=4.0.11=py27_0
- enum34=1.1.6=py27_0
- gensim=2.2.0=np112py27_0
- get_terminal_size=1.0.0=py27_0
- ipykernel=4.6.1=py27_0
- ipython=5.3.0=py27_0
- ipython_genutils=0.2.0=py27_0
- jupyter=1.0.0=py27_0
- jupyter_client=5.2.3=py27_0
- jupyter_core=4.4.0=py27_0
- numpy==1.12.1=py27_0
- openssl=1.0.2l=0
- path.py=10.3.1=py27_0
- pathlib2=2.2.1=py27_0
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=9.0.1=py27_1
- prompt_toolkit=1.0.14=py27_0
- ptyprocess=0.5.1=py27_0
- pygments=2.2.0=py27_0
- python=2.7.13=0
- python-dateutil=2.6.0=py27_0
- pyzmq=16.0.2=py27_0
- readline=6.2=2
- scandir=1.5=py27_0
- scipy==0.19.1=np112py27_0
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_1
- tk=8.5.18=0
- tornado=4.5.1=py27_0
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - backports.weakref==1.0rc1
  - bleach==1.5.0
  - boto==2.48.0
  - bz2file==0.98
  - certifi==2017.4.17
  - chardet==3.0.4
  - cycler==0.10.0
  - formencode==1.3.1
  - funcsigs==1.0.2
  - functools32==3.2.3.post2
  - h5py==2.7.0
  - html5lib==0.9999999
  - idna==2.5
  - imdbpy==6.6
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.3
  - jupyter-core==4.4.0
  - keras==2.0.6
  - lxml==3.8.0
  - markdown==2.6.8
  - matplotlib==2.0.2
  - mock==2.0.0
  - nltk==3.2.4
  - olefile==0.44
  - pandas==0.20.3
  - pbr==3.1.1
  - pillow==4.2.1
  - prompt-toolkit==1.0.14
  - protobuf==3.3.0
  - pydispatcher==2.0.5
  - pyparsing==2.2.0
  - pytz==2017.2
  - pyyaml==3.12
  - requests==2.18.1
  - scikit-learn==0.18.2
  - seaborn==0.8
  - sklearn==0.0
  - smart-open==1.5.3
  - sqlalchemy==1.1.11
  - sqlalchemy-migrate==0.11.0
  - sqlobject==3.3.0
  - sqlparse==0.2.3
  - stop-words==2015.2.23.1
  - subprocess32==3.2.7
  - tempita==0.5.2
  - tensorflow==1.2.1
  - theano==0.9.0
  - tmdbsimple==1.7.0
  - urllib3==1.21.1
  - werkzeug==0.12.2
  - wget==3.2
prefix: /anaconda/envs/deeplearningproject
